cm_interface_play:
    path:     /play
    defaults: { _controller: "CMInterfaceBundle:Game:play" }

cm_interface_guest:
    path:     /guest/play
    defaults: { _controller: "CMInterfaceBundle:Game:guestPlay" }
    
cm_interface_login:
    path:     /
    defaults: { _controller: "FOSUserBundle:Security:login" }
    
cm_validate_move:
    path:     /checkMove
    defaults: { _controller: "CMInterfaceBundle:Ajax:validateMove" }
    
cm_js_testBoard:
    path:     /tests
    defaults: { _controller: "CMInterfaceBundle:JSTests:testJS" }

    