cm_interface_start:
    path:     /start
    defaults: { _controller: "CMInterfaceBundle:Game:start" }
    
cm_new_search:
    path:     /newSearch
    defaults: { _controller: "CMInterfaceBundle:Game:newSearch" }
    
cm_match_search:
    path:     /matchSearch/{searchID}
    defaults: { _controller: "CMInterfaceBundle:Game:matchSearch" }
    
cm_cancel_search:
    path:     /cancelSearch/{searchID}
    defaults: { _controller: "CMInterfaceBundle:Game:cancelSearch", searchID = 0 }
    
cm_interface_play:
    path:     /play/{gameID}
    defaults: { _controller: "CMInterfaceBundle:Game:play" }
    
cm_interface_join:
    path:     /join/{gameID}
    defaults: { _controller: "CMInterfaceBundle:Game:joinGame" }
    
cm_interface_checkJoined:
    path:     /checkJoined/{gameID}
    defaults: { _controller: "CMInterfaceBundle:Game:checkJoined" }
    
cm_send_move:
    path:     /sendMove
    defaults: { _controller: "CMInterfaceBundle:Move:sendMove" }
    
cm_get_move:
    path:     /getMove
    defaults: { _controller: "CMInterfaceBundle:Move:getMove" }
    
cm_save_move:
    path:     /saveMove/{gameID}
    defaults: { _controller: "CMInterfaceBundle:Move:saveMove" }
    
cm_find_cheat:
    path:     /findCheat/{gameID}
    defaults: { _controller: "CMInterfaceBundle:Move:findCheat" }
    
cm_offer_draw:
    path:     /draw
    defaults: { _controller: "CMInterfaceBundle:Game:offerDraw" }
    
cm_resign_game:
    path:     /resign/{gameID}
    defaults: { _controller: "CMInterfaceBundle:Game:resign" }
    
cm_toggle_chat:
    path:     /toggleChat/{gameID}/{player}
    defaults: { _controller: "CMInterfaceBundle:Game:toggleChat" }
    
cm_send_chat:
    path:     /sendChat/{gameID}
    defaults: { _controller: "CMInterfaceBundle:Game:sendChat" }
    
cm_listen:
    path:     /listen
    defaults: { _controller: "CMInterfaceBundle:Game:listen" }
    
cm_js_testBoard:
    path:     /tests
    defaults: { _controller: "CMInterfaceBundle:JSTests:testJS" }

    