cm_interface_start:
    path:     /start
    defaults: { _controller: "CMInterfaceBundle:Game:start" }
    
cm_interface_play:
    path:     /play/{gameID}
    defaults: { _controller: "CMInterfaceBundle:Game:play" }
    
cm_new_game:
    path:     /newGame
    defaults: { _controller: "CMInterfaceBundle:Game:newGame" }
    
cm_offer_draw:
    path:     /draw
    defaults: { _controller: "CMInterfaceBundle:Game:offerDraw" }
    
cm_resign_game:
    path:     /resign/{gameID}
    defaults: { _controller: "CMInterfaceBundle:Game:resign" }
    
cm_toggle_chat:
    path:     /toggleChat/{player}
    defaults: { _controller: "CMInterfaceBundle:Game:toggleChat" }
    
cm_validate_move:
    path:     /checkMove
    defaults: { _controller: "CMInterfaceBundle:Move:validateMove" }
    
cm_get_first_move:
    path:     /getFirstMove
    defaults: { _controller: "CMInterfaceBundle:Move:getFirstMove" }
    
cm_js_testBoard:
    path:     /tests
    defaults: { _controller: "CMInterfaceBundle:JSTests:testJS" }

    