services:
#    cm_interface.example:
#        class: CM\InterfaceBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    game.factory:
        class: CM\InterfaceBundle\Factories\GameFactory

