services:
    game_search_factory:
        class: CM\InterfaceBundle\Factories\GameSearchFactory
    game_factory:
        class: CM\InterfaceBundle\Factories\GameFactory
    pawn_validator:
        class: CM\InterfaceBundle\Helpers\Validation\PawnValidator
    rook_validator:
        class: CM\InterfaceBundle\Helpers\Validation\RookValidator
    knight_validator:
        class: CM\InterfaceBundle\Helpers\Validation\KnightValidator
    bishop_validator:
        class: CM\InterfaceBundle\Helpers\Validation\BishopValidator
    queen_validator:
        class: CM\InterfaceBundle\Helpers\Validation\QueenValidator
    king_validator:
        class: CM\InterfaceBundle\Helpers\Validation\KingValidator
    html_helper:
        class: CM\InterfaceBundle\Helpers\HTMLHelper

