services:
#    cm_interface.example:
#        class: CM\InterfaceBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    game_factory:
        class: CM\InterfaceBundle\Factories\GameFactory
    pawn_validator:
        class: CM\InterfaceBundle\Helpers\Validation\PawnValidator
    rook_validator:
        class: CM\InterfaceBundle\Helpers\Validation\RookValidator
    knight_validator:
        class: CM\InterfaceBundle\Helpers\Validation\KnightValidator

