fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

cm_interface:
    resource: "@CMInterfaceBundle/Resources/config/routing.yml"
    prefix:   /game

cm_interface_guest:
    path:     /guest
    defaults: { _controller: "CMInterfaceBundle:Game:guest" }
    