fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

cm_app:
    resource: "@CMAppBundle/Resources/config/routing.yml"
    prefix:   /game

cm_app_guest:
    path:     /guest
    defaults: { _controller: "CMAppBundle:Game:guest" }
    