imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true
    
parameters:
    cm_user.last_active_listener.class: CM\UserBundle\EventListener\LastActiveListener

# Services
services:
    cm_user.last_active_listener:
        class: "%cm_user.last_active_listener.class%"
        arguments: ["@security.context", "@fos_user.user_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ CMAppBundle ]
    #java: /usr/bin/java
    filters:
        lessphp: 
            file: "%kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php" 
            apply_to: ".less$"
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8		
        mapping_types:
           enum:  string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
fos_user: 
    db_driver: orm
    firewall_name: main
    user_class: CM\UserBundle\Entity\User
