cm_app:
    resource: "@CMAppBundle/Resources/config/routing.yml"
    prefix:   /game
    
cm_app_login:
    path:     /
    defaults: { _controller: "FOSUserBundle:Security:login" }

cm_user:
    resource: "@CMUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"