cm_interface:
    resource: "@CMInterfaceBundle/Resources/config/routing.yml"
    prefix:   /game

cm_user:
    resource: "@CMUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
